### PR TITLE
set the height of the hero image to force contentful to resize to a s…

### PR DESCRIPTION
**Pull request by numsweb**
…maller image. This reduces the page load time, since most of the page load time involves the image.

### CODE REVIEW

**Comment by mattlangan** [comment]
@numsweb have you looked at or shown Leslie side-by-sides of the page with different height params? Are we sure that using a height of, say, 1000 will render too poorly? I'm getting that same image down to 400k @ `?h=1000`.

**Comment by numsweb** [comment]
@mattlangan 
It looks like someone has reworked the image (in contentful?).  if I look at production for acc the image is only 765K and it has a different name. I'm checking with Noe, but I think we can close this one out (sorry just saw your comment).

**Comment by numsweb** [comment]
@mattlangan Noe confirmed that Dawit has already resized the image, so this PR is no longer needed.

**Comment by numsweb** [comment]
No longer necessary as image has been resized.

**Pull request closed without merging**
