### PR TITLE
Add street labels to facility floor plan images

### PR DESCRIPTION
**Pull request by mattlangan**

### CODE REVIEW

**Comment by mattlangan** [comment]
@numsweb Take a look at this locally and on staging (I haven't deployed it - you can force-push at will) and make sure I've captured all of your changes. If it all looks good then you can just do a rebase to `reword` the commits to provide additional context (refer back to the guide for writing a commit).

**Comment by numsweb** [comment]
OK, now its showing up on the PR, my branch must have been whacked.  I deployed on staging and it looks OK, and also ran locally to inspect the images. I'll delete the PR I created because I thought you were saying for me to do this same thing, so I did.

**Comment by mattlangan** [comment]
@numsweb it looks like you simply added duplicate commits rather than re-wording the original ones I had in here. Why is there a merge commit? I also don't see any commit messages, only titles.

**Comment by numsweb** [comment]
Matt, this is what you said:
If it all looks good then you can just do a rebase to reword the commits to provide additional context (refer back to the guide for writing a commit).

So I did a rebase and expanded the commit messages.

**Comment by numsweb** [comment]
Closing this request as it is out of date and the changes have already been incorporated.

**Pull request closed without merging**
